[package]
name = "remowt-polkit-shared"
description = "Shared polkit/PAM types for remowt"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nix = { workspace = true, features = ["user"] }
serde = { workspace = true, features = ["derive"] }
zbus.workspace = true
