{
  lib,
  fleetLib,
  ...
}:
let
  inherit (fleetLib.options) mkDataOption;
  inherit (lib.options) mkOption;
  inherit (lib.types)
    nullOr
    listOf
    str
    attrsOf
    submodule
    bool
    unspecified
    ;

  secretDataValue = {
    options = {
      raw = mkOption {
        type = nullOr str;
        description = "Raw secret data in unspecified encoded and optionally encrypted format.";
        default = null;
      };
    };
  };

  sharedSecretData = {
    freeformType = attrsOf (submodule secretDataValue);
    options = {
      managed = mkOption {
        type = nullOr bool;
        description = "Is current fleet data value is generated by generator";
        default = null;
      };

      createdAt = mkOption {
        type = str;
        description = "Timestamp of secret generation/last rotation.";
        default = null;
      };
      expiresAt = mkOption {
        type = nullOr str;
        description = "Expiration timestamp triggering mandatory secret rotation.";
        default = null;
      };

      owners = mkOption {
        type = listOf str;
        description = ''
          List of hosts currently authorized to decrypt this shared secret.

          If owners differ from expected owners, the secret is considered outdated
          and requires regeneration or re-encryption.
        '';
        default = [ ];
      };
      generationData = mkOption {
        type = unspecified;
        description = "Contextual metadata associated with secret part.";
        default = null;
      };
    };
  };

  managerKey = {
    options = {
      name = mkOption {
        type = str;
        description = "Who does this manager key belongs to.";
      };
      key = mkOption {
        type = str;
        description = "Age-compatible key";
      };
    };
    config = { };
  };
in
{
  options.data = mkDataOption ({ config, ... }:
    {
      options = {
        managerKeys = mkOption {
          type = listOf (submodule managerKey);
        };
        secrets = mkOption {
          type = attrsOf (listOf submodule sharedSecretData);
          default = { };
          description = "Shared secret data.";
        };
      };
    });
}
