[package]
name = "remowt-endpoints"
description = "Nix daemon proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bifrostlink.workspace = true
camino.workspace = true
serde = { workspace = true }
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
	"net",
	"io-util",
	"rt",
	"process",
	"io-std",
] }
tracing.workspace = true
nix = { workspace = true, features = ["process", "signal", "term"] }
zbus.workspace = true
remowt-link-shared.workspace = true
iroh.workspace = true
