[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.2.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition.workspace = true
rust-version.workspace = true
default-run = "fleet"

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
clap_complete.workspace = true
fleet-base.workspace = true
nix-eval.workspace = true
remowt-fleet.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

futures.workspace = true
itertools.workspace = true
shlex.workspace = true
tabled.workspace = true

human-repr = { workspace = true, optional = true }
indicatif = { workspace = true, optional = true }
opentelemetry.workspace = true
opentelemetry-appender-tracing.workspace = true
opentelemetry-exporter-env.workspace = true
opentelemetry_sdk.workspace = true
tracing-indicatif = { workspace = true, optional = true }
tracing-opentelemetry.workspace = true

[features]
default = ["indicatif"]
# Not quite stable
indicatif = [
	"dep:tracing-indicatif",
	"dep:indicatif",
	"dep:human-repr",
	"nix-eval/indicatif",
]
