[package]
name = "nixlike"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true

linked-hash-map = "0.5.6"
peg = "0.8.5"
ron = "0.11.0"
serde = "1.0.219"
serde-transcode = "1.1.1"
serde_json = "1.0.140"
